import {
  BOC_VERSION,
  tryLoadSubtitleCandidates,
  resetClipState,
  refreshClip,
  loadSubtitle
} from "./subtitle-fetcher.js";

import {
  CACHE_KEY_PREFIX,
  fetchSubtitleBundle,
  fetchVideoMeta,
  retryAsync,
  getSubtitleCacheKey
} from "./subtitle-fetch.js";
import {
  onSubtitleChange,
  getPopupPayload,
  applyNoSubtitleState,
  readVideoDescription,
  copyMarkdown,
  downloadSubtitle
} from "./subtitle-ui.js";
import { refreshDerivedContent } from "./note-build.js";

import {
  buildUiHtml,
  bindUiEvents,
  ensureUiReady,
  setBusyState,
  setStatus,
  renderMeta,
  renderSubtitleSelect,
  setMessage
} from "./ui-renderer.js";

import { ids } from "./reader.js";
import {
  buildReaderStepperControl,
  bindReaderStepperControl,
  updateReaderPreferences,
  renderReaderPanels,
  renderReadingInfoPanel,
  updateReaderFollowState,
  syncReadingViewPlayback,
  closeReadingView,
  renderReadingView,
  stopReadingViewSync,
  noteManualReaderInteraction,
  logWarn,
  onReadingChapterClick,
  onReadingTranscriptClick,
  hydrateReaderStateFromSettings,
  applyReadingViewPresentation,
  renderReadingStatus,
  syncReaderModeAfterMount,
  settleReaderModePresentation,
  bindReaderHeaderActionsHover,
  startReadingViewSync,
  startReaderPlayerObserver,
  stopReaderPlayerObserver,
  moveReadingMainInline,
  alignReaderViewportToPlayer,
  scheduleReaderMiniPlayerDismiss,
  openReaderViewShell,
  applyReaderPageFocus,
  ensureReaderPlayerMounted,
  layoutReaderPlayerHost,
  maybeRefreshReaderSubtitleInBackground
} from "./reading-view-adapter.js";

export {
  BOC_VERSION,
  CACHE_KEY_PREFIX,
  retryAsync,
  fetchVideoMeta,
  tryLoadSubtitleCandidates,
  getSubtitleCacheKey,
  resetClipState,
  refreshClip,
  loadSubtitle,
  fetchSubtitleBundle,
  onSubtitleChange,
  getPopupPayload,
  applyNoSubtitleState,
  readVideoDescription,
  refreshDerivedContent,
  copyMarkdown,
  downloadSubtitle,
  buildUiHtml,
  bindUiEvents,
  ensureUiReady,
  setBusyState,
  setStatus,
  renderMeta,
  renderSubtitleSelect,
  setMessage,
  ids,
  buildReaderStepperControl,
  bindReaderStepperControl,
  updateReaderPreferences,
  renderReaderPanels,
  renderReadingInfoPanel,
  updateReaderFollowState,
  syncReadingViewPlayback,
  closeReadingView,
  renderReadingView,
  stopReadingViewSync,
  noteManualReaderInteraction,
  logWarn,
  onReadingChapterClick,
  onReadingTranscriptClick,
  hydrateReaderStateFromSettings,
  applyReadingViewPresentation,
  renderReadingStatus,
  syncReaderModeAfterMount,
  settleReaderModePresentation,
  bindReaderHeaderActionsHover,
  startReadingViewSync,
  startReaderPlayerObserver,
  stopReaderPlayerObserver,
  moveReadingMainInline,
  alignReaderViewportToPlayer,
  scheduleReaderMiniPlayerDismiss,
  openReaderViewShell,
  applyReaderPageFocus,
  ensureReaderPlayerMounted,
  layoutReaderPlayerHost,
  maybeRefreshReaderSubtitleInBackground
};
